#!/bin/sh
# Fixture engine for tests + harness. Mimics `claude -p <prompt>
# [--output-format json]` closely enough for the tier-router spawn.
# Modes via FAKE_CLAUDE_MODE: ok (default) | fail | short.
# FAKE_CLAUDE_SLEEP=<seconds> delays the reply so mid-cycle "running"
# states are observable (screenshot harness); unset = instant.
set -eu

[ -n "${FAKE_CLAUDE_SLEEP:-}" ] && sleep "$FAKE_CLAUDE_SLEEP"

MODE="${FAKE_CLAUDE_MODE:-ok}"
JSON=0
for a in "$@"; do
  [ "$a" = "json" ] && JSON=1
done

if [ "$MODE" = "fail" ]; then
  echo "fixture engine forced failure" >&2
  exit 1
fi

if [ "$MODE" = "short" ]; then
  OUT="Fixture engine output (canned) — too short on purpose."
else
  OUT="Fixture engine output (canned) — produced by the test harness, not a model.

Summary: This deliverable was generated by the fixture engine so the
orchestrator, QA gates, and review flow can be exercised end to end
without spending real tokens. Every character here is canned.

Plan: The plan section exists to satisfy structural checks that look
for declared sections, demonstrating the Sections: contract honestly.

Next steps: Review this deliverable in the Work view; approving it
marks the task done, requesting changes requeues it with feedback."
fi

if [ "$JSON" = "1" ]; then
  # tier-router JSON envelope with zero usage — the canvas T2 path
  # degrades to the stub exactly as with no engine.
  printf '{"result": "fixture engine json mode — canned", "total_cost_usd": 0, "usage": {"input_tokens": 0, "output_tokens": 0, "cache_read_input_tokens": 0}}\n'
else
  printf '%s\n' "$OUT"
fi
